// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8mx6TqkESkBAjiUV7fRAF3bBwj2L42p8',
    appId: '1:316155377702:android:0e0b88dbdc0d80b1ce0ee7',
    messagingSenderId: '316155377702',
    projectId: 'ihk-ap1-prep',
    storageBucket: 'ihk-ap1-prep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeCPGMiTuOdV6Yt27dKB1AF9w2klPKVk',
    appId: '1:316155377702:ios:4804326a735784c7ce0ee7',
    messagingSenderId: '316155377702',
    projectId: 'ihk-ap1-prep',
    storageBucket: 'ihk-ap1-prep.firebasestorage.app',
    iosBundleId: 'com.example.ihkAp1Prep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpeCPGMiTuOdV6Yt27dKB1AF9w2klPKVk',
    appId: '1:316155377702:ios:4804326a735784c7ce0ee7',
    messagingSenderId: '316155377702',
    projectId: 'ihk-ap1-prep',
    storageBucket: 'ihk-ap1-prep.firebasestorage.app',
    iosBundleId: 'com.example.ihkAp1Prep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKDErg3PWG4C7ttsXFzNrXq3wf6cpbPM',
    appId: '1:316155377702:web:b7765f1ef5c54b43ce0ee7',
    messagingSenderId: '316155377702',
    projectId: 'ihk-ap1-prep',
    authDomain: 'ihk-ap1-prep.firebaseapp.com',
    storageBucket: 'ihk-ap1-prep.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKDErg3PWG4C7ttsXFzNrXq3wf6cpbPM',
    appId: '1:316155377702:web:b7765f1ef5c54b43ce0ee7',
    messagingSenderId: '316155377702',
    projectId: 'ihk-ap1-prep',
    authDomain: 'ihk-ap1-prep.firebaseapp.com',
    storageBucket: 'ihk-ap1-prep.firebasestorage.app',
  );

}